### ISSUE TITLE
Is AuthenticityToken broken?

### ISSUE THREAD

**Issue by odigity** [sinatra/rack-protection#100]
I'm new to Rack and Sinatra (previously used Rails, but got fed up with the magic and my own ignorance of my tools).

I've spent most of today learning about rack-protection, how it works, how Sinatra uses it, and trying to configure it properly.

I wanted to confirm that the CSRF token was really being checked, so I disabled RemoteForm and added AuthenticityToken (the base class of RemoteForm that doesn't check referrer), which I believe should cause all of my POSTed forms to immediately fail since I haven't yet added CSRF tags to them.

But it didn't.  The forms continued to work just fine.

Does this mean AuthenticityToken is broken?  And if so, does this mean all Rails apps are vulnerable?

(After I gave up, I decided to try out rack_csrf, followed the same approach, and got the results I expected.)

**Comment by odigity** [comment]
Turns out this might be because I'm using reaction: :drop_session (which I copied from Sinatra's code), which I guess doesn't accomplish anything.  I switch to :deny, and now I'm getting Forbidden, which is good.

**Comment by zzak** [comment]
@odigity Thanks for your report!
