### ISSUE TITLE
Consider changing the repo description

### ISSUE THREAD

**Issue by adelevie** [sinatra/rack-protection#101]
The repo description `You should use protection!` might give people a poor impression. I'm a big fan of Sinatra and its related projects, but this description makes me hesitant to want to use this at work.

**Comment by ashleygwilliams** [comment]
closed by https://github.com/sinatra/rack-protection/pull/102

**Comment by adelevie** [comment]
Thanks so much!

**Comment by ashleygwilliams** [comment]
no srsly thank you. it's good to have a community take care of itself :sparkling_heart: :dolphin:
