### ISSUE TITLE
Forbidden + signout using sidekiq/devise/activeadmin on production server with nginx/haproxy/thin

### ISSUE THREAD

**Issue by ysynesis** [sinatra/rack-protection#107]
We using sidekiq gem on production server with nginx, haproxy, thin. Also we using sidekiq UI for authenticated admin users (activeadmin): 

authenticate :admin_user do
  mount Sidekiq::Web => '/sidekiq'
end

Sidekiq UI uses sinatra.
After authentication we try to open /sidekiq. Instead of seeing sidekiq ui we receive only "forbidden". Furthermore, we lost devise session. So if we try to open /admin, activeadmin require authentication again. But if we try to disable rack-protection it works fine.

We facing this issue only on production server.

We using: 
nginx(https)
haproxy(http)
thin (http)
sidekiq 4.1.1
devise 3.5.6
activeadmin 1.0.0.pre2
sinatra 1.4.7

**Comment by zzak** [comment]
I'm not familiar with Sidekiq UI, so perhaps it's better to ask on their issue tracker.

Happy to help, of course.

Also pinging @mperham in-case he's seen this kind of thing before.

Thanks! <3

**Comment by mperham** [comment]
https://github.com/mperham/sidekiq/wiki/Monitoring#forbidden

**Comment by zzak** [comment]
Thanks @mperham :100:! <3 <3

I'll try to add something similar to our docs here as well, as Sinatra proper.

**Comment by shalini-maiti** [comment]
Hey @zzak, 

I would like to take this up. Do let me know the correct place in the docs to add this to.
