### ISSUE TITLE
Sinatra problem with rack-protection

### ISSUE THREAD

**Issue by pamit** [sinatra/rack-protection#110]
Hi!

I encountered this today after bundle update:

sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack-protection (~> 2.0)

You've specified the alpha version (s.version = "2.0.0"), yet no version 2.0.0 was released.

Thanks in advance.

For those who faced this, I had to fetch this commit:
gem 'sinatra', github: 'sinatra', :ref => 'a5da6fa'

**Comment by zzak** [comment]
Sorry for the trouble, you need to use `rack-protection` from HEAD until the release is made for now:

`gem 'rack-protection', github: 'sinatra/rack-protection'`
