### ISSUE TITLE
Could not find gem 'rack-protection' in git://github.com/sinatra/rack-protection.git (at master@f405fec)

### ISSUE THREAD

**Issue by jaredbeck** [sinatra/rack-protection#117]
Because ~~the history of this repo has been destroyed~~ this repo no longer contains a gemspec, the CI for [paper_trail](https://github.com/airblade/paper_trail/) no longer works.

```
Fetching git://github.com/sinatra/sinatra.git
Fetching git://github.com/sinatra/rack-protection.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Could not find gem 'rack-protection' in
git://github.com/sinatra/rack-protection.git (at master@f405fec).
Source does not contain any versions of 'rack-protection'
The command "eval bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}" failed. Retrying, 3 of 3.
```

~~One solution would be to restore the history of this repo and simply put your "this thing has moved" message as the latest commit.~~

I'd be grateful for any other suggestions of course. Thanks.

**Comment by jaredbeck** [comment]
Nevermind, the root cause was https://github.com/thoughtbot/appraisal/issues/119. Please disregard.

**Comment by zzak** [comment]
As the README says, you must update your repo to point to sinatra/sinatra,
such as:

github 'sinatra/sinatra' do
  gem 'rack-protection'
end

Thank you and sorry for the trouble!
