### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by m-o-e** [sinatra/rack-protection#55]
Please
* Explain how each protection works and the corner cases
* Explain how to correctly implement each protection in a Rack/Sinatra app
* Explain how to test each protection in a live app (to ensure they are properly enabled)

**Comment by zzak** [comment]
I would agree there is serious lack of examples, but the docs should be accessible now as of closing #161.

I'll close this now and open up a new ticket upstream to explain the situation -- which hopefully will gain more traction than this repo.
