### ISSUE TITLE
Invalid referer raises error

### ISSUE THREAD

**Issue by georgeu2000** [sinatra/rack-protection#61]
When the referer header has invalid characters such as a `|`, as in `http://example.com/invalid|uri`, rack-protection raises an error on base line 86.

Not sure about a good way to handle this situation. In my app, it would be fine to delete the invalid characters...

**Comment by zzak** [comment]
Fix should already be in `v1.5.3` according to https://github.com/sinatra/rack-protection/commit/6d953d2379be3eb0576d5e1e1d6abbb74bd9c745
