### ISSUE TITLE
"You need to set up a session middleware *before* Rack::Protection::SessionHijacking"

### ISSUE THREAD

**Issue by rickygu** [sinatra/rack-protection#77]
Rails 4.0.2
config.ru

require ::File.expand_path('../config/environment',  __FILE__)
require 'rack/protection'
use Rack::Protection
run Rails.application

gives me this error:

"you need to set up a session middleware *before* Rack::Protection::SessionHijacking"

**Comment by zzak** [comment]
I commited 82e72ba which allows you to skip the session based middleware by passing a `:without_session => true` option.
