### ISSUE TITLE
AuthenticityToken check in a rails app when no session['_csrf_token'] is set 

### ISSUE THREAD

**Issue by anthony** [sinatra/rack-protection#83]
We have a rails application that is fronted by a 3rd party authentication server.

Upon the first page load no `session['_csrf_token']` has been set. 

This worked fine until we upgraded from 1.5.0 to .1.5.3 and this commit came in: https://github.com/rkh/rack-protection/commit/c415d50c7ce97d35c8fae706dbed3390330b983d

The issue here is that `session[:csrf]` is being assigned a `random_number` as the `session['_csrf_token']` is not set, but all requests after the first page load will have a `authenticity_token` set from rails so the comparison between that and what is in the session will always fail.

I haven't provided a patch because I'm not sure how or if you'd like this addressed. For us we have just disabled the `RemoteToken` check as rails handles that anyway.

**Comment by zzak** [comment]
This is the correct way to handle it IMO, you have to pick one CSRF protection either use Rails or Rack::Protection but they're not intended to be used together afaict.

**Comment by zzak** [comment]
@anthony As it turns out, they _can_ be used together you just have to share the same secret token with this plugin, such as:

`set :session_secret, Rails.application.secrets[:secret_key_base]`

Should probably add this to the documentation...

**Comment by jkowens** [comment]
@zzak as @anthony mentioned as of c415d50c7ce97d35c8fae706dbed3390330b983d Rack::Protection beats Rails to setting an authenticity token in the session. So when Rails does generate one, the two are out of sync.

**Comment by jkowens** [comment]
After giving this more thought, maybe a better option is to always set a value for `session[:_csrf_token]` alongside `session[:csrf]` or maybe the session key should be configurable so it can just be set to `_csrf_token` to be compatible with Rails.

I'm leaning towards the latter option, making the key a configurable option with a default value of :csrf.

```
default_options :session_csrf_key => :csrf
                :authenticity_param => 'authenticity_token',
                :authenticity_token_length => 32,
                :allow_if => nil
```
 
Thoughts?

**Comment by jkowens** [comment]
Hm ok, so that option would pose some difficulty with the class method `Rack::Protection::AuthenticityToken.token`. I'm leaning back towards setting `session[:_csrf_token]` alongside `session[:csrf]`. 😜 

It's one extra session variable, but I think it's the simplest solution (that I've been able to come up with) for maintaining Rails compatibility.

**Comment by jkowens** [comment]
Besides this issue, rack-protection now supports custom sized token lengths (2.0.0.beta2), whereas Rails generates a fixed 32 character token. 

Based on these differences now, I don't know that it is reasonable to try to provide compatibility between the two methods of CSRF protection. I think they should just be mutually exclusive.

I suggest updating the class documentation for Rack::Protection::AuthenticityToken and it's subclasses to remove the comment that it is compatible with Rails.

**Comment by zzak** [comment]
Yes, so I think the original intention was to have them be compatible.. but I'm not sure who broke compat first.

My guess is that when Rails adopted the BREACH mitigation strategy tokens were no longer compatible.

We can either try to adopt their strategy more closely, or drop compatibility. I'm fine with both, probably the later is easier. My question then would be, how to share sessions between Rails and Sinatra? I think some people might be trying to do this, or need this feature.

**Comment by jkowens** [comment]
The code you shared above does handle sharing cookie based sessions between Rails and Sinatra.

This issue was specifically about keeping the csrf token values session[:csrf] and session[:_csrf_token] in sync. I see the value in being able to do that, or if possible have the csrf session key be configurable so that Sinatra and Rails are playing with the same token.
