### ISSUE TITLE
JsonCsrf for GET image.

### ISSUE THREAD

**Issue by georgeu2000** [sinatra/rack-protection#84]
Upon upgrading from eb7e4c9a176d to 1.5.3, our Sinatra app is getting `attack prevented by Rack::Protection::JsonCsrf `.

Not sure how to fix this (besides `set :protection, :except => [:json_csrf]`).

The resource in question returns an image, and does not take params. Any advice would be appreciated. Thank you.

**Comment by chrisallick** [comment]
any updates on this?

**Comment by zzak** [comment]
Sorry for the delay, I will take a look into these issues after sinatra-contrib is passing on sinatra master.

**Comment by zzak** [comment]
@georgeu2000 or @chrisallick I'm not sure if I know how to repro this. Looking at the code, it seems the request must have `application/json` content-type in order to trigger the protection of `JsonCsrf`.

I wonder if it's getting caught else-where.. or if a CSP would help alleviate the situation.

**Comment by zzak** [comment]
Closing this after copying the ticket upstream, but feel free to discuss which ever.
