### ISSUE TITLE
[Warning] Session Hijacking default of HTTP_ACCEPT_LANGUAGE is broken for iOS 8+

### ISSUE THREAD

**Issue by tommeier** [sinatra/rack-protection#88]
Hi, 

Just a warning to any others that may hit this. The latest iOS safari builds change the HTTP_ACCEPT_LANGUAGE between requests (doesn't occur on iOS 6 or 7), this of course breaks the default `SessionHijacking` keys being checked and thus destroys the session.

**Comment by zzak** [comment]
Hello!

Is this still an issue in newer iOS? I'm unfamiliar with their development, so I'm not sure.

Also, this seems like a bug in iOS no? `SessionHijacking` is doing the right thing IMO.

Please reopen if you have any more information. Thanks!

**Comment by tommeier** [comment]
@zzak :+1: definitely an issue with iOS8 just a nightmare to track down 💃  Rack protection is definitely acting correctly.
