### ISSUE TITLE
Rack::Protection::SessionHijacking

### ISSUE THREAD

**Issue by frodsan** [sinatra/rack-protection#92]
Hi, I found that Rack::Protection was reducing the performance of my application to the half. I just did a little benchmark with a single Cuba app, and the results show that the problem was Rack::Session::Hijacking.

Here is the result of the [benchmark](https://gist.github.com/frodsan/0b15ce5cab247b7832f5):

```
# Calculating -------------------------------------
#      with middleware     1.074k i/100ms
#   without middleware     4.947k i/100ms
# -------------------------------------------------
#      with middleware     11.151k (± 3.8%) i/s -     55.848k
#   without middleware     57.781k (± 3.8%) i/s -    291.873k
```

I don't think I need this middleware because I'm using HTTPS everywhere. Any reason why is included in the defaults?

Thanks.

**Comment by lfender6445** [comment]
i am curious can you exclude https and drop memory allocation?

**Comment by zzak** [comment]
Hello!

I'm open to any suggestions on how to improve performance of this middlware.

btw, if you _don't need_ it there are a number of ways to remove it, for example: http://www.sinatrarb.com/intro.html#Configuring%20attack%20protection

For a Rails app, I think you can do `config.middleware.delete Rack::Protection`, but I'm not sure if this includes all of the middleware provided by this plugin. Please do investigate <3
